### ISSUE TITLE
Definition of `EasyScoreMessage`

### ISSUE THREAD

**Issue by rvilarl** [jaredjj3/vexml#1]
@jaredjj3 I have included the concept in `vexml.ts` with minor modifications.
Can you elaborate on `EasyScoreMessage`? What structure do you foresee?

**Comment by jaredjj3** [comment]
Thanks for your patience. I started a new branch `jj`, where I've defined the [types](https://github.com/jaredjj3/vexml/blob/c51b6ddee94fc390f275947f4bdffcd9c6081a20/lib/vexml/types.ts) I think are needed for the POC.

I'm still working on wiring it together, but I'll merge it into `main` when done.

**Comment by jaredjj3** [comment]
I got it to roughly work, but I mocked a lot of complex processes with JavaScript symbols:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/19232300/157256168-82a5a991-09fb-4268-8f6b-e81d39c4f579.png">

The entrypoint is https://github.com/jaredjj3/vexml/blob/f6cdfff19a326012c5b05c0a6c136106b4d4ee1b/lib/vexml/vexml.ts#L4

My main thought is that the current EasyScore API is designed for static declaration. I found it extremely awkward that I couldn't add notes to a voice one at a time - I had to know all of the notes to declare a stave. Another thought is the `MusicXMLCursor` will be the most challenging piece to implement. In MusicXML, you sometimes have to "jump" around the document to get the full context of a notation. For example, if you encounter a beamed note, you'll have to figure out the other notes before rendering it. As implemented, a naive cursor puts the complexity burden on the caller to keep track of notations waiting on full context.

What are your thoughts?

**Comment by rvilarl** [comment]
Let us go for the beam. I suggest that you define the easyScoreMessages and I tie it to VexFlow using API or introducing new features in EasyScore.

**Comment by jaredjj3** [comment]
>Let us go for the beam. I suggest that you define the easyScoreMessages and I tie it to VexFlow using API or introducing new features in EasyScore.

My reservation is that _parts_ of EasyScore seem to need the full context in order to declare a notation. For example, a clef and time signature are attributes of a stave, but in order to declare a stave, you need to know all the voices. In order to declare a voice, you need to know all the notes in the voice. If I'm a human dev statically writing it, it's fine. However, if I'm trying to write a program to feed into it, it's very complex because the caller is tasked with maintaining all the context to declare EasyScore notations.

**Do you know if EasyScore can have an optional more granular API?**

instead of _onlyt_ this API

```ts
system
  .addStave({
    voices: [
      score.voice(score.notes('C#5/q, B4, A4, G#4', { stem: 'up' })),
      score.voice(score.notes('C#4/h, C#4', { stem: 'down' })),
    ],
  })
  .addClef('treble')
  .addTimeSignature('4/4');
```

I would want the _option_ of this API

```ts
const stave = system.addStave();
stave.addClef('treble').addTimeSignature('4/4')
stave.addVoice().addNote('C#5/q').addNote('B4/q').addNote('A4/q').addNote('G#4/q').setNoteOptions({ stem: 'up' });
stave.addVoice().setNoteOptions({ stem: 'down' }).addNote('C#4/h').addNote('C#4/h');
```

>And wouldn't it make sense to have accidentals as a separated message?

Based on the [<pitch>](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/pitch/) element schema, alter is a separate element, so that sounds reasonable.

The power of having a `MusicXMLCursor`, is that we could change it to return logical musical groupings instead of the structures imposed by the MusicXML spec. However, that pushes a lot of complexity on the `MusicXMLCursor` class, which I don't think makes sense right now.

**Comment by rvilarl** [comment]
Beams are there and I made some minor changes to align more with your approach above adding the notes one at a time. @jaredjj3 what is the next step that you would suggest?

**Comment by jaredjj3** [comment]
Thanks for the commits! The `beamStart` and `beamEnd` messages make sense, and it handles the case where beams span multiple measures. Besides the ESM module issue, I think this would work.

I think we need to stop and evaluate whether or not to pursue this endeavor. There are a number of highly complex processes:

- **Parsing (and implicitly validating) MusicXML.** In `vexml`, we're using [MusicXMLParser](https://github.com/jaredjj3/vexml/blob/baa6023581ed2c4ea12cecc8cd86c7ca525fba75/lib/vexml/MusicXMLParser.ts) to accomplish this. Right now, the return value is mocked, but we can easily leverage [@stringsync/musicxml](https://github.com/stringsync/musicxml) to do this for us. The tradeoff is a bigger bundle, and therefore not really feasible to integrate directly into [vexflow](https://github.com/0xfe/vexflow). I think this means `vexml` should live separately from `vexflow` if we decide to continue development on it.

- **Traversing a MusicXML structure.** In `vexml`, we're using [MusicXMLCursor](https://github.com/jaredjj3/vexml/blob/baa6023581ed2c4ea12cecc8cd86c7ca525fba75/lib/vexml/MusicXMLCursor.ts) to accomplish this. The return values are mocked into terms that we would understand, but I don't think that's necessarily the best logical grouping. For example: instead of mocking a `<measure>`, we could've made it iterate over each `<note>` or `<measure>` + `<note>`, but each of these logical groupings change the complexity on the caller. This seems like a very difficult problem, and the edge cases seem countless. I'm very wary about this approach.

- **Translating a MusicXML node from the cursor to an `EasyScoreMessage`.** In `vexml`, we're using [EasyScoreMessageProducer.getMessages](https://github.com/jaredjj3/vexml/blob/baa6023581ed2c4ea12cecc8cd86c7ca525fba75/lib/vexml/EasyScoreMessageProducer.ts#L35-L47). As stated in the previous point, the design of the `MusicXMLCursor` will affect the complexity of this. I question if we even need this structure, since we could just call different `EasyScore` "commands" from the MusicXML itself. The idea of having a raw JSON structure was to decouple the structure of MusicXML from `EasyScore`. You could send these messages over sockets and have multiple remote editors change the same `EasyScore` instance. In the end, it just feels like we're reimplementing the MusicXML spec in a more convenient format. I suppose it could also support other music score specs, but I don't think we must support that.

- **Translating EasyScoreMessage into `EasyScore` calls.** Even though we control the `EasyScoreMessage` structures, it still feels like we're shoehorning it to work with `EasyScore`. There is a clear disconnect between `EasyScore` and MusicXML, and I think this discrepancy is ultimately causing a lot of complexity, even with the `EasyScoreMessage` abstraction. This POC has made it more apparent to me that `EasyScore` is really for static declaration.

All in all, I think these complexities would take O(years) to fully unravel with 2 engineers working on it part-time. The `EasyScoreMessage` abstraction does offer the ability to scale up the number of engineers working on it (some can work on `MusicXMLCursor` -> `EasyScoreMessage` while some work on `EasyScoreMessage` -> `EasyScore` actions), but it's marginal at least.

For all of these reasons, I don't think we should continue evolving this POC. However, I'm open to your thoughts. What do you think?

**Comment by rvilarl** [comment]
Let us continue for a while :)
